// A C T I O N S   TYPES
export const CART_ACTIONS_TYPES = {
  ADD_ITEM_TO_CART: "ADD_ITEM_TO_CART",
  REMOVE_ITEM_FROM_CART: "REMOVE_ITEM_FROM_CART",
  REMOVE_ITEM: "REMOVE_ITEM",
  SET_CART_COUNT: "SET_CART_COUNT",
  SET_TOTAL_PRICE: "SET_TOTAL_PRICE",
};
